image: angegar/devcontainers

tasks:
  - name: Install python requirements
    init: pip install -r requirements.txt
    
  - name: Install marp
    init: wget https://github.com/marp-team/marp-cli/releases/download/v${MARP_VERSION}/marp-cli-v${MARP_VERSION}-linux.tar.gz -O marp.tar.gz &&	tar xvf marp.tar.gz -C /usr/local/bin
vscode:
  extensions:
    - marp-team.marp-vscode
    - hediet.vscode-drawio
    - jebbs.plantuml
    - yzhang.markdown-all-in-one
    - streetsidesoftware.code-spell-checker
